Remove "version" from examples and unified cluster name as "cluster-<number>"
eksctl-io/eksctl pull request #7249
Opened 2023-11-04 11:11 UTC by guessi

### Description

Existing sample ClusterConfigs under `examples/` having EOL/EOS version, should be removed.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [X] Manually tested
- [X] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2023-11-10 10:55 UTC, Himangini requested changes
Nice spot ⭐
Instead of removing maybe bump the versions to more recent ones?
Also, cluster name changes are not required for examples

2023-11-10 16:05 UTC, guessi commented
@Himangini the `default version` of `ClusterConfig` is depends on the version of `eksctl`.

I can add version to all sample configs, I'm wondering is that sounds good to you?

Maybe we should we keep `region` aligned as well? WDYT?

2023-11-10 16:28 UTC, guessi commented
@Himangini Just update the commit to keep it simple, only `"version"` field been updated/added.

2023-11-10 16:29 UTC, guessi commented on examples/27-oidc-provider.yaml
> +  name: cluster-27
To keep it aligned with the file name.

2023-11-10 16:29 UTC, guessi commented on examples/30-vpc-with-ip-family.yaml
> +  name: cluster-30
To keep it aligned with the file name.

2023-11-28 12:39 UTC, guessi commented
@Himangini I don't understand what you mean. Shouldn't we keep all the contents of examples up to date? why only update outdated version?

2023-12-29 19:29 UTC, guessi commented
Closing as the PR kept open too long.

2023-12-29 19:29 UTC, closed without merging